export const roomsTypes = {
  GET_ROOMS_START: "GET_ROOMS_START",
  GET_ROOMS_SUCCESS: "GET_ROOMS_SUCCESS",
  GET_ROOMS_FAILURE: "GET_ROOMS_FAILURE",
  ADD_MESSAGE_TO_ROOM_START: "ADD_MESSAGE_TO_ROOM_START",
  ADD_MESSAGE_TO_ROOM_FAILURE: "ADD_MESSAGE_TO_ROOM_FAILURE",
  ADD_MESSAGE_TO_ROOM_SUCCESS: "ADD_MESSAGE_TO_ROOM_SUCCESS",
  ADD_NEW_ROOM: "ADD_NEW_ROOM",
  DELETE_ROOM: "DELETE_ROOM",
};
