version: "3.8"

services:
  # Backend api
  chat-app-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/chat-app-api
    links:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      REDIS_URI: ${REDIS_URI}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/usr/src/chat-app-api

  # Postgres
  postgres:
    container_name: postgres
    build: ./postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
  
  # Redis
  redis:
    image: redis
    ports: 
      - "${REDIS_PORT}:${REDIS_PORT}" 
  