export const userTypes = {
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  CHANGE_USERNAME: "CHANGE_USERNAME",
};
